### ISSUE TITLE
Is the training data released

### ISSUE THREAD

**Issue by gaozhiguang** [patronus-ai/Lynx-hallucination-detection#5]
Hi, nice work in hallucination detection！

In the paper, it is mentioned that the resource has released the training dataset, but I was unable to find it. Could you confirm if it has not yet been released? If so, is there a planned release date?

**Comment by sri-harsha-jaladi** [comment]
> Hi, nice work in hallucination detection！
> 
> In the paper, it is mentioned that the resource has released the training dataset, but I was unable to find it. Could you confirm if it has not yet been released? If so, is there a planned release date?

Hi there, again great work on the hallucination detection!

I encountered the same issue. The paper mentions that the training dataset has been released, but I couldn't locate it either. Could you please confirm if it has been released yet? If not, is there an expected release date?

Thanks!

**Comment by Rebecca-Qian** [comment]
Hi all,

Thank you for reaching out! I wanted to share an update that we have released all artifacts to generate training data for Lynx, including scripts and prompts. The training dataset is not released due to risks with licensing on downstream applications - we will update our paper with a note on this. Apologies for the confusion. Please let us know if you encounter any issues reproducing our results, and we can help out and answer any further questions.
